export const IGNORED_CLASS_PATTERNS = [
  // ── Exact standalone utility classes ──
  /^flex$/,
  /^grid$/,
  /^block$/,
  /^inline$/,
  /^inline-block$/,
  /^inline-flex$/,
  /^inline-grid$/,
  /^hidden$/,
  /^visible$/,
  /^invisible$/,
  /^relative$/,
  /^absolute$/,
  /^fixed$/,
  /^sticky$/,
  /^static$/,
  /^overflow-/,
  /^cursor-/,
  /^pointer-events-/,
  /^select-/,
  /^resize$/,
  /^table$/,
  /^contents$/,

  // ── Tailwind / utility spacing ──
  /^m-/,
  /^mt-/,
  /^mr-/,
  /^mb-/,
  /^ml-/,
  /^mx-/,
  /^my-/,
  /^-m/,

  /^p-/,
  /^pt-/,
  /^pr-/,
  /^pb-/,
  /^pl-/,
  /^px-/,
  /^py-/,

  /^gap-/,
  /^space-/,

  // ── Typography utilities ──
  /^text-/,
  /^font-/,
  /^fw-/,
  /^fst-/,
  /^lh-/,
  /^leading-/,
  /^tracking-/,
  /^whitespace-/,
  /^break-/,
  /^truncate$/,

  // ── Colors / backgrounds ──
  /^bg-/,
  /^from-/,
  /^via-/,
  /^to-/,
  /^text-opacity-/,
  /^bg-opacity-/,

  // ── Borders / rounded ──
  /^border/,
  /^rounded/,
  /^ring-/,
  /^outline-/,
  /^divide-/,

  // ── Layout utilities ──
  /^d-/,
  /^flex-/,
  /^grid-/,
  /^col-/,
  /^row-/,
  /^container/,
  /^w-/,
  /^h-/,
  /^min-/,
  /^max-/,
  /^size-/,
  /^aspect-/,
  /^grow$/,
  /^shrink$/,
  /^basis-/,
  /^order-/,
  /^self-/,

  // ── Flex / grid alignment ──
  /^justify-/,
  /^align-/,
  /^items-/,
  /^content-/,
  /^place-/,

  // ── Transforms / transitions / animations ──
  /^transform/,
  /^transition/,
  /^duration-/,
  /^ease-/,
  /^delay-/,
  /^animate-/,
  /^translate-/,
  /^rotate-/,
  /^scale-/,
  /^skew-/,
  /^origin-/,

  // ── Effects / filters ──
  /^shadow/,
  /^opacity-/,
  /^blur-/,
  /^brightness-/,
  /^contrast-/,
  /^drop-shadow-/,
  /^grayscale/,
  /^invert/,
  /^saturate-/,
  /^sepia/,
  /^backdrop-/,

  // ── Z-index / position ──
  /^z-/,
  /^inset-/,
  /^top-/,
  /^right-/,
  /^bottom-/,
  /^left-/,

  // ── Bootstrap components ──
  /^btn/,
  /^alert-/,
  /^card-/,
  /^nav-/,
  /^badge-/,
  /^modal-/,

  // ── Framework-generated class prefixes ──
  /^Mui/,
  /^css-/,
  /^sc-/,
  /^chakra-/,
  /^emotion-/,
  /^ant-/,
  /^ng-/,
  /^jsx-/,
  /^svelte-/,
  /^_/,
  /^[a-z]{1,2}\d{3,}/ // e.g. "a1b2c3" auto-generated hashes
]
