name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      publish_pw_core:
        description: 'Publish pw-core to npm'
        required: true
        type: boolean
        default: true
      publish_create_pw_core:
        description: 'Publish create-pw-core to npm'
        required: true
        type: boolean
        default: true

jobs:
  publish-pw-core:
    if: ${{ github.event.inputs.publish_pw_core == 'true' }}
    uses: ./.github/workflows/publish-pw-core.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-create-pw-core:
    if: ${{ !cancelled() && !failure() && github.event.inputs.publish_create_pw_core == 'true' }}
    needs: publish-pw-core
    uses: ./.github/workflows/publish-create-pw-core.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

