name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      pw_core_bump:
        description: 'pw-core version bump (select skip to disable publishing)'
        required: true
        default: 'none'
        type: choice
        options:
          - skip
          - none
          - patch
          - minor
          - major
      create_pw_core_bump:
        description: 'create-pw-core version bump (select skip to disable publishing)'
        required: true
        default: 'none'
        type: choice
        options:
          - skip
          - none
          - patch
          - minor
          - major

jobs:
  publish-pw-core:
    if: ${{ github.event.inputs.pw_core_bump != 'skip' }}
    uses: ./.github/workflows/publish-pw-core.yml
    with:
      bump: ${{ github.event.inputs.pw_core_bump }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-create-pw-core:
    if: ${{ !cancelled() && !failure() && github.event.inputs.create_pw_core_bump != 'skip' }}
    needs: publish-pw-core
    uses: ./.github/workflows/publish-create-pw-core.yml
    with:
      bump: ${{ github.event.inputs.create_pw_core_bump }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
